### ISSUE TITLE
StructType inside ArrayType are broken

### ISSUE THREAD

**Issue by carrotstealer** [ldo/dbussy#29]
Hello. I have method with out_signature "a(ii)" and get following exception when it called.
This patch works for me
[dbussy.txt](https://github.com/ldo/dbussy/files/4688431/dbussy.txt)

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/cctv/.local/lib/python3.6/site-packages/dbussy.py", line 2573, in wrap_function
    result = function(self, message, user_data)
  File "/home/cctv/.local/lib/python3.6/site-packages/ravel.py", line 2040, in _message_interface_dispatch
    return_result_common(call_info, result)
  File "/home/cctv/.local/lib/python3.6/site-packages/ravel.py", line 1897, in return_result_common
    args = result
  File "/home/cctv/.local/lib/python3.6/site-packages/ravel.py", line 1770, in _send_method_return
    reply.append_objects(sig, *args)
  File "/home/cctv/.local/lib/python3.6/site-packages/dbussy.py", line 4451, in append_objects
    append_sub(parse_signature(signature), args, self.iter_init_append())
  File "/home/cctv/.local/lib/python3.6/site-packages/dbussy.py", line 4415, in append_sub
    if type_is_fixed_array_elttype(arrelttype.code.value) :
AttributeError: 'StructType' object has no attribute 'code'

**Comment by ldo** [comment]
I think the problem is that non-basic `Type` objects do not have a `code` field defined. I have fixed that. Does that cure your problem?

**Comment by carrotstealer** [comment]
Thanks for the quick response! your patch fixed the issue
