### ISSUE TITLE
Apparently harmless Exception in ravel.py

### ISSUE THREAD

**Issue by mcondarelli** [ldo/dbussy#39]
Hi,
I'm still trying to learn something about `dbus` and your package.

Using one example, as-is and without changes results in an `Exception`, but apparently everything still works:

```python
mcon@cinderella:~/projects/dbussy$ cat >t.py
#!/usr/bin/python3
#+
# DBussy example -- make an Introspect query to a specified bus object.
# This version uses the structured high-level Ravel API with asyncio.
# Invoke this script as follows:
#
#    introspect_ravelled «bus» «bus-name» «obj-path»
#
# where «bus» is either “session” or “system”, indicating which bus
# to do the query on, “bus-name” is the name of the service on the
# bus to query, and «obj-path» is the path of the object to query.
# The response should be an XML string in the usual introspection
# format, indicating the protocol for communicating with the
# specified object.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import dbussy as dbus
from dbussy import \
    DBUS
import ravel

loop = asyncio.get_event_loop()

if len(sys.argv) != 4 :
    raise getopt.GetoptError("usage: %s session|system «bus-name» «obj-path»" % sys.argv[0])
#end if

bus = {"session" : ravel.session_bus, "system" : ravel.system_bus}[sys.argv[1].lower()]()
bus.attach_asyncio(loop)
interface = loop.run_until_complete \
  (
    bus[sys.argv[2]][sys.argv[3]]
        .get_async_interface(DBUS.INTERFACE_INTROSPECTABLE)
  )
reply = loop.run_until_complete(interface.Introspect())
sys.stdout.write(reply[0])
```

```
mcon@cinderella:~/projects/dbussy$ python3 t.py system org.bluez /org/bluez
Exception ignored on calling ctypes callback function: <function Connection.add_filter.<locals>.wrap_function at 0x7f85ef860940>
Traceback (most recent call last):
  File "/home/mcon/projects/dbussy/dbussy.py", line 2573, in wrap_function
    result = function(self, message, user_data)
  File "/home/mcon/projects/dbussy/ravel.py", line 2246, in _message_interface_dispatch
    dispatch_signal(bus._dispatch, dbus.split_path(message.pth))
AttributeError: 'Message' object has no attribute 'pth'
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node><interface name="org.freedesktop.DBus.Introspectable"><method name="Introspect"><arg name="xml" type="s" direction="out"/>
</method></interface><interface name="org.bluez.AgentManager1"><method name="RegisterAgent"><arg name="agent" type="o" direction="in"/>
<arg name="capability" type="s" direction="in"/>
</method><method name="UnregisterAgent"><arg name="agent" type="o" direction="in"/>
</method><method name="RequestDefaultAgent"><arg name="agent" type="o" direction="in"/>
</method></interface><interface name="org.bluez.ProfileManager1"><method name="RegisterProfile"><arg name="profile" type="o" direction="in"/>
<arg name="UUID" type="s" direction="in"/>
<arg name="options" type="a{sv}" direction="in"/>
</method><method name="UnregisterProfile"><arg name="profile" type="o" direction="in"/>
</method></interface><node name="hci0"/></node>mcon@cinderella:~/projects/dbussy$ 
```

In spite of the error the program still works (and also my own code, a bit more complex works, with exactly the same `Exception`).

This is completely repeatable for me on two very different systems: an up-to-date Linux-Mint "Ulyssa" and a self-built micro MIPS.
Both systems have the same version of Your code (DBussy-1.3 and ravel-2.0.8, installed via `pip` not from git)

**Comment by ldo** [comment]
I have no idea how that typo could have come in. It’s not in any version of the file in this repo. It would not be in any of the releases I put on pypi.

**Comment by mcondarelli** [comment]
Apparently a global substitution `pth` -> `path` apparently solves the problem.
Most likely I must have done something very wrong.
I will pull packages again from scratch (tomorrow) and see what happens.
Thanks.

**Comment by mcondarelli** [comment]
I can confirm it *must* have been some mishap on my side.
Redownloading from scratch does not show any bogus behavior.
Sorry for the useless noise. I will close this.

Side issue: I need to "register an Agent" using the appropriate interface : 
net.connman.iwd => /net/connman/iwd => net.connman.iwd.AgentManager
    None = RegisterAgent(path: o)

Agent is supposed to provide passphrase for WiFi connection.
Documentation is at: https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/doc/agent-api.txt

If I understand correctly I should create a `ravel` object implementing the methods, register it to `dbus` with a chosen path and register it to `iwd` calling `RegisterAgent(chosen_path)`.
Is this right? If so what is the closest example I can use as starting point?
Thanks in Advance,

**Comment by ldo** [comment]
I suppose any of my server-side [examples](https://github.com/ldo/dbussy_examples) could serve as a basis for implementing a Ravel interface class. The only difference I can see is that you register yourself as a server with connman and tell it what object path it should use to make calls to you.

**Comment by mcondarelli** [comment]
I'm trying to use bigben_server_ravelled as template.
I also don't understand (yet) how to handle errors.

**Comment by mcondarelli** [comment]
My first attempt was not good:
```python
#!/usr/bin/python3

import asyncio
import ravel


path = '/net/connman/iwd'
bname = 'net.connman.iwd'
abus = ravel.system_bus()
abus.attach_asyncio(asyncio.get_event_loop())


@ravel.interface(ravel.INTERFACE.SERVER, name='my.connman.iwd.agent')
class Agent:
    iface = abus[bname][path].get_interface('net.connman.iwd.Agent')

    def __init__(self):
        iface = ravel.system_bus()[bname][path].get_interface('net.connman.iwd.AgentManager')
        iface.RegisterAgent(self)

    @ravel.method(in_signature='', out_signature='')
    def Release(self):
        pass

    @ravel.method(in_signature='o', out_signature='s', args_keyword='net', set_result_keyword='ret')
    def RequestPassphrase(self, net, ret):
        passph = 'bogus_pass'
        print(f'Agent.RequestPassphrase({net}): => {passph}')
        ret(passph)

    @ravel.method(in_signature='s', out_signature='', args_keyword='reason')
    def Cancel(self, reason):
        print(f'Agent.Cancel({reason}):')


async def get_nets():
    # iface_adapter = bus[bname][path+'/0'].get_interface('net.connman.iwd.Adapter')
    # iface_device = bus[bname][path+'/0/5'].get_interface('net.connman.iwd.Device')
    iface_station = await abus[bname][path+'/0/5'].get_async_interface('net.connman.iwd.Station')

    nets = await iface_station.GetOrderedNetworks()
    print(nets)
    nets = await iface_station.GetHiddenAccessPoints()
    print(nets)
    await iface_station.Scan()
    while await iface_station.Scanning:
        await asyncio.sleep(1)
        print('.', end='', flush=True)
    print()
    result = {}
    nets = await iface_station.GetOrderedNetworks()
    for net in nets[0]:
        # print(net)
        # name = net[0]
        # print(name)
        iface_net = await abus[bname][net[0]].get_async_interface('net.connman.iwd.Network')
        nam = await iface_net.Name
        typ = await iface_net.Type
        result[nam] = (net[0], typ, net[1])
    return result


if __name__ == '__main__':
    async def main():
        nets = await get_nets()
        maxs = -9999
        net = None
        for k, v in nets.items():
            print(f'***({k})--({v[0]})[{v[1]}]--({v[2]})***')
            if v[2] > maxs:
                maxs = v[2]
                net = v
        hold_me = Agent()
        iface_net = await abus[bname][net[0]].get_async_interface('net.connman.iwd.Network')
        await iface_net.Connect()
        for n in range(100):
            await asyncio.sleep(10)

    asyncio.get_event_loop().run_until_complete(main())
```
Apparently I got completely wrong how to define my `Agent` server:
```
# venv/bin/python handle_ravelled.py 
Traceback (most recent call last):
  File "handle_ravelled.py", line 14, in <module>
    class Agent:
  File "handle_ravelled.py", line 15, in Agent
    iface = abus[bname][path].get_interface('net.connman.iwd.Agent')
  File "/root/ravel/ravel.py", line 1643, in get_interface
    self.conn.get_proxy_interface \
  File "/root/ravel/ravel.py", line 1391, in get_proxy_interface
    raise dbus.DBusError \
dbussy.DBusError: org.freedesktop.DBus.Error.UnknownInterface -- peer “net.connman.iwd” object “/net/connman/iwd” does not understand interface “net.connman.iwd.Agent”
# 
```
Tomorrow I'll give another try (I'm almost exactly at antipodes from You ;) )

(of course any comment would be welcome)

**Comment by ldo** [comment]
The error message from libdbus seems to indicate that the bus peer you are talking to does not understand the interface specified in the docs.

Try using the `introspect_all` example script on `net.connman.iwd`, and see what interfaces it actually supports?

**Comment by mcondarelli** [comment]
That actually means I shouldn't try to access 'net.connman.iwd.Agent'.
I should IMPLEMENT  'net.connman.iwd.Agent' and use  'net.connman.iwd.AgentManager' to register it (at least this is my interpretation).
I tried (I will change the above comment to reflect) but still something is missing, probably I need to register myself with D-Bus as server and I have a foggy idea about how to do that.

**Comment by ldo** [comment]
Yes, that sounds right. Registering with D-Bus as a server is easy, you can use any of my server examples for that.

**Comment by mcondarelli** [comment]
Sorry being a nuisance, but I really don't understand what `D-Bus` is trying to tell me :(

I updated the code above together  with current output.
I also added the output of `dbus-monitor --system` while I tried the code.

Can You help, somehow?
Thanks in Advance

**Comment by ldo** [comment]
Please do not keep overwriting your post. Each time you do, you make nonsense of my replies to it!

**Comment by mcondarelli** [comment]
Oops!
Sorry, I just wanted to avoid very long thread.
What is the policy about code/log listings?
