### ISSUE TITLE
Cannot run loop in IDE

### ISSUE THREAD

**Issue by graham8** [ldo/dbussy#55]
Thank you for this project!  Just starting out, I can run the introspect example fine from the linux terminal but not inside my IDE (Spyder3)

```
runfile('/home/graham/GitProjects/dbussy_examples/introspect', args='system org.bluez /org/bluez', wdir='/home/graham/GitProjects/dbussy_examples')
Traceback (most recent call last):

  File "<ipython-input-1-9cb732248004>", line 1, in <module>
    runfile('/home/graham/GitProjects/dbussy_examples/introspect', args='system org.bluez /org/bluez', wdir='/home/graham/GitProjects/dbussy_examples')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/graham/GitProjects/dbussy_examples/introspect", line 47, in <module>
    reply = conn.loop.run_until_complete(await_reply)

  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()

  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```
Is there a workaround?

**Comment by ldo** [comment]
Create a new event loop?

**Comment by graham8** [comment]
Can you point me to advice on how I would change the code to do that. Bit of a noob on event loops.

**Comment by graham8** [comment]
> Create a new event loop?

So how about:
`conn.attach_asyncio(asyncio.new_event_loop())`

Nope:
`Cannot run the event loop while another loop is running`

Something I'm not getting about this.
